export const ADD_ACCOUNT_INIT = 'ADD_ACCOUNT_INIT';
export const ADD_ACCOUNT_SUBMIT = 'ADD_ACCOUNT_SUBMIT';
export const DELETE_ACCOUNT = 'DELETE_ACCOUNT';
export const EDIT_ACCOUNT_INIT = 'EDIT_ACCOUNT_INIT';
export const EDIT_ACCOUNT_SUBMIT = 'EDIT_ACCOUNT_SUBMIT';
